import type { Metadata, Viewport } from 'next';
import '#@/styles/globals.css';
import 'material-symbols';
import { ReactNode } from 'react';
import { Josefin_Sans,
  Playfair_Display,
  PT_Serif_Caption,
  Radio_Canada,
  Raleway, } from 'next/font/google';
import Script from 'next/script';


const prefix = process.env.NODE_ENV === 'production'
  ? 'salvemos-los-ecosistemas'
  : 'beta';

const hostname = `https://${ prefix }.suarez-ramirez.com`;

export const metadata: Metadata = {
  metadataBase: new URL(
    hostname
  ),
  title          : 'proyecto cali',
  description    : 'Generated by create next app',
  generator      : 'proyecto cali',
  applicationName: 'proyecto cali',
  keywords       : [
    'especial multimedia',
    'periodismo grafico',
    'periodismo'
  ],
  authors: [
    {
      name: 'Camilo Suarez',
    },
    {
      name: 'Cachorro Cami',
      url : hostname,
    },
  ],

  creator        : 'Cachorro Cami',
  publisher      : 'CachorroC',
  alternates     : {},
  formatDetection: {
    email    : false,
    address  : false,
    telephone: false,
  },
  appleWebApp: {
    capable       : true,
    title         : 'proyecto cali',
    statusBarStyle: 'black-translucent',
    startupImage  : [
      'src/app/icon.svg',
      {
        url  : '/icon.svg',
        media: '(device-width: 768px) and (device-height: 1024px)',
      },
    ],
  },
  appLinks: {
    web: {
      url            : '/',
      should_fallback: true,
    },
  },
};

export const viewport: Viewport = {
  width            : 'device-width',
  initialScale     : 1,
  maximumScale     : 1,
  colorScheme      : 'light dark',
  interactiveWidget: 'resizes-content',
  themeColor       : [
    {
      media: '(prefers-color-scheme: light)',
      color: '#5c6145',
    },
    {
      media: '(prefers-color-scheme: dark)',
      color: '#c7c8b7',
    },
  ],
};

const josefinSans = Josefin_Sans(
  {
    variable: '--font-josefin-sans',
    subsets : [
      'latin'
    ],
  }
);

const playDisp = Playfair_Display(
  {
    subsets: [
      'latin-ext',
      'latin'
    ],
    preload : true,
    variable: '--play-display',
    weight  : 'variable',
  }
);

const ptserif = PT_Serif_Caption(
  {
    subsets: [
      'latin'
    ],
    display : 'auto',
    preload : false,
    variable: '--ptserif',
    weight  : '400',
  }
);

const radio = Radio_Canada(
  {
    subsets: [
      'latin-ext'
    ],
    preload : false,
    variable: '--radio',
  }
);

const raleway = Raleway(
  {
    subsets: [
      'latin'
    ],
    preload : true,
    variable: '--raleway',
  }
);

export default function RootLayout(
  {
    children,
  }: Readonly<{
    children: ReactNode;
  }>
) {
  return (
    <html lang="es">
      <body
        className={`${ josefinSans.className } ${ playDisp.variable }  ${ raleway.variable } ${ radio.variable } ${ ptserif.variable } [ color-scheme: light dark ]`}
      >
        { children }
        <Script src={`${ hostname }/install-service-worker.js`} />
      </body>
    </html>
  );
}
