import type { Metadata, Viewport } from 'next';
import '#@/styles/globals.css';
import 'material-symbols';
import { ReactNode } from 'react';
import { Josefin_Sans,
  Playfair_Display,
  PT_Serif_Caption,
  Radio_Canada,
  Raleway, } from 'next/font/google';
import Script from 'next/script';
import Navbar from '#@/components/Navbar';
import { NavigationContextProvider } from './context/navigation-context';
import { ArticlesProvider } from './context/articles-context';
import { Article } from '#@/types/article';
import { articleCollection } from '#@/lib/connection/collections';
import styles from '#@/styles/layout.module.css';


const prefix = process.env.NODE_ENV === 'production'
  ? 'salvemos-los-ecosistemas'
  : 'beta';

const hostname = `https://${ prefix }.suarez-ramirez.com`;

export const metadata: Metadata = {
  metadataBase: new URL(
    hostname
  ),
  title          : 'salvemos los ecosistemas',
  description    : 'Generated by create next app',
  generator      : 'salvemos los ecosistemas',
  applicationName: 'salvemos los ecosistemas',
  creator        : 'Cachorro Cami',
  publisher      : 'CachorroC',
  keywords       : [
    'especial multimedia',
    'periodismo grafico',
    'periodismo',
    'periodismo ambiental'
  ],
  authors: [
    {
      name: 'Juan Camilo Suárez',
    },
    {
      name: 'Cachorro Cami',
      url : hostname,
    },
  ],
  appleWebApp: {
    capable       : true,
    title         : 'salvemos los ecosistemas',
    statusBarStyle: 'black-translucent',
    startupImage  : [
      'src/app/icon.svg',
      {
        url  : '/icon.svg',
        media: '(device-width: 768px) and (device-height: 1024px)',
      },
    ],
  },
  appLinks: {
    web: {
      url            : '/',
      should_fallback: true,
    },
  },
};

export const viewport: Viewport = {
  width            : 'device-width',
  initialScale     : 1,
  maximumScale     : 1,
  colorScheme      : 'light dark',
  interactiveWidget: 'resizes-content',
  themeColor       : [
    {
      media: '(prefers-color-scheme: light)',
      color: '#5c6145',
    },
    {
      media: '(prefers-color-scheme: dark)',
      color: '#c7c8b7',
    },
  ],
};

const josefinSans = Josefin_Sans(
  {
    variable: '--font-josefin-sans',
    subsets : [
      'latin'
    ],
  }
);

const playDisp = Playfair_Display(
  {
    subsets: [
      'latin-ext',
      'latin'
    ],
    preload : true,
    variable: '--play-display',
    weight  : 'variable',
  }
);

const ptserif = PT_Serif_Caption(
  {
    subsets: [
      'latin'
    ],
    display : 'auto',
    preload : false,
    variable: '--ptserif',
    weight  : '400',
  }
);

const radio = Radio_Canada(
  {
    subsets: [
      'latin-ext'
    ],
    preload : false,
    variable: '--radio',
  }
);

const raleway = Raleway(
  {
    subsets: [
      'latin'
    ],
    preload : true,
    variable: '--raleway',
  }
);

async function getArticles () {

  const arrayList: Article[] = [];

  const collection = await articleCollection();

  const listCollection = collection.find();

  for await ( const element of listCollection ) {
    const stringified = JSON.stringify(
      element
    );

    const parsed = JSON.parse(
      stringified
    );

    arrayList.push(
      parsed
    );
  }

  return arrayList;
}

export default async function RootLayout(
  {
    children,
  }: Readonly<{
    children: ReactNode;
  }>
) {
  const initialArticles = await getArticles();

  return (
    <html lang="es">
      <body
        className={`${ josefinSans.className } ${ playDisp.variable }  ${ raleway.variable } ${ radio.variable } ${ ptserif.variable } [ color-scheme: light dark ]`}
      >
        <NavigationContextProvider>
          <ArticlesProvider initialArticles={ initialArticles }>
            <div className={styles.container}>
              <Navbar />
              { children }

            </div>
          </ArticlesProvider>
        </NavigationContextProvider>
        <Script src={`${ hostname }/install-service-worker.js`} />
      </body>
    </html>
  );
}
